### ISSUE TITLE
Use gogoprotubuf instead of the default one

### ISSUE THREAD

**Issue by GCat** [lonnng/nano#22]
I've read that cockroachdb uses gogoprotubuf in their database for speed

it won the benchmark test
https://github.com/alecthomas/go_serialization_benchmarks

and I think it will work well with nano
https://github.com/gogo/protobuf

**Comment by lonnng** [comment]
Thanks for your advice, `gogo protobuf` will be an another Serializer implementation. 
If you have ideas, welcome to contribute code.
ref:
- https://github.com/lonnng/nano/blob/master/serialize/serializer.go
- https://github.com/lonnng/nano/blob/master/serialize/protobuf/protobuf.go
