### ISSUE TITLE
請問有辦法把session層，抽到redis之類的集成去操作嗎?

### ISSUE THREAD

**Issue by kensomanpow** [lonnng/nano#28]
我想把nano application 做成分散式的架構，但是想要共用session，請問能加上這方面的支持嗎?

**Comment by lonnng** [comment]
1. 可以把nano application设计成分布式架构
2. 目前nano可以直接作为gate服务器
3. 其他的后端服务器, 可以使用gate服务器通过grpc/smux调用后端服务器, 在后端服务器实现一个session.NetEntity结构, 对应目前的agent即可

PS: 可以直接使用smux: https://github.com/xtaci/smux

**Comment by kensomanpow** [comment]
謝謝回覆，我試試看你說的解法！

**Comment by kensomanpow** [comment]
感謝你之前的回覆，我完成了grpc的分散式架構，並用nano當作我的gateway server
但我目前又遇到問題，再麻煩了～

請問我有辦法透過nano取得單一的session和所有的session嗎? (因為會有從後端服務要主動發送到gateway，所以必須從handler以外的地方取得session 和 group)

**Comment by lonnng** [comment]
一个比较简单直接的办法就是在包含rpc的Component中使用一个sync.Map保存SessionID => Session
但是你需要注意, 需要在Component的AfterInit生命周期函数中注册SessionClose的回调, 当session关闭, 你需要从map中移除, 并通知rpc后端服务器

**Comment by kensomanpow** [comment]
好的，是個可行的方案，我再嘗試，謝謝
