### ISSUE TITLE
Is it possible to use udp as trasnport? 

### ISSUE THREAD

**Issue by mirth** [lonnng/nano#33]
In case i want to develop multiplayer shooter/

**Comment by lonnng** [comment]
Yes, you can try https://github.com/xtaci/kcp-go, which has compatible interface with net.Conn.

https://github.com/lonnng/nano/blob/6b20a4b2f1a5805864e7acddba59649421019f9d/app.go#L80
```go
kcp.Listen(laddr string)
```

**Comment by mirth** [comment]
Thanks, i'm now trying to broadcast from server some messages and after some time getting `Error=session send buffer exceed`. Even if i send one message per second. What is the root of the problem? Is it problem of kcp?

**Comment by lonnng** [comment]
Be sure closed session has been removed from your group

**Comment by mirth** [comment]
The problem was with kcp-go.
